Add molecules section
m3ntorship/pickly-playground-v2 pull request #13
Opened 2021-02-02 21:31 UTC by ayaosama05

-- add molecules section

2021-02-04 12:37 UTC, AymanMorsy requested changes

2021-02-04 12:37 UTC, AymanMorsy commented on static/public/index.html
> +           <li><a href="#">
needs to update background-color of SVG container

2021-02-04 12:37 UTC, AymanMorsy commented on static/public/index.html
> +     <div class="col-span flex flex-row text-dark items-center justify-start gap-xs">
add border-radius on the caption card

2021-02-07 18:32 UTC, hebasaadosman commented
good job aya 👍 
very small notes
1- background of image upload not white 
2- 25% dislike need to justify on image

2021-02-13 12:31 UTC, hebasaadosman submitted a review, later dismissed
LGTM

2021-02-13 16:16 UTC, hebasaadosman submitted a review, later dismissed

2021-02-20 16:43 UTC, hebasaadosman approved these changes

2021-02-20 16:44 UTC, merged