Storybook/atoms
m3ntorship/pickly-playground-v2 pull request #8
Opened 2021-01-30 03:12 UTC by atwfk

###Description

#created atoms components:-
-Avatar
-Button
-Checkbox
-FormInput
-Progress
-Radio
-TabGroup
-Toggle

2021-01-30 19:03 UTC, AbdoMgdy requested changes

2021-01-30 19:03 UTC, AbdoMgdy commented on storybook/src/Twfiek/Atoms/Button/Button.js
> +  let padding = "";
comment

2021-01-30 19:03 UTC, AbdoMgdy commented on storybook/src/Twfiek/Atoms/Button/Button.js
> +  } else {
comments

2021-01-31 18:28 UTC, moatazalaa14 approved these changes
LGTM  :eyes:

2021-02-01 04:21 UTC, merged